language: node_js
node_js:
    - "16"
env:
    global:
        - NODE_ENV=test
before_install:
    - git config --global url."https://github.com/".insteadOf ssh://git@github.com
    - git config --global url."https://".insteadOf git://
script:
    - npm ci
    - npm run lint -- --quiet
    - npm run test:unit
branches:
    only:
        - master
    except:
        - build
addons:
    apt:
        packages:
            - libgif-dev
